### PR TITLE
Add an "adareducer" script at the toplevel

### PR DESCRIPTION
**Pull request by setton**
For the benefit of the development environment, or any
users who only "git clone" this repository and work from it.

Fix the testsuite using this.

Rename the "adareducer" source dir to "ada_reducer"

### CODE REVIEW

**Comment by pmderodat** [comment]
Tracking our live discussion: this feels like a step back from going the pip (standard) way. Why not require users/infrastructure to run `pip install .` before running the testsuite? The point of pip is that it’s supposed to be easy to use, so hacking a bash-only script looks odd.

Also renaming the top-level package like this will be confusing: if we go this way, I would suggest to have clearly different names, such as “libadareducer” for the Python package, and “adareduce[r]” for the script.

**Comment by glacambre** [comment]
@pmderodat speaking purely from a personal pov, I'm getting issues while trying to use pip:
```
ERROR: Could not find a version that satisfies the requirement libadalang (from adareducer) (from versions:
none)
ERROR: No matching distribution found for libadalang
WARNING: You are using pip version 21.3.1; however, version 22.0.2 is available.
You should consider upgrading via the '/home/lacambre/e3/bin/python -m pip install --upgrade pip' command.
```
But the python script worked fine when ran manually. I'd prefer to be able to run adareducer manually rather than having to use pip.

**Comment by pmderodat** [comment]
Not sure why you want to avoid using pip: as I said to Nico privately, it is possible to install adareducer in dev mode (https://setuptools.pypa.io/en/latest/userguide/development_mode.html) to avoid the install step each time you change the code (if that’s your concern). Also, you can install Libadalang through pip using the wheel from a Libadalang wavefront (for instance) to fix the dependency issue.

I still think this would look like hack, now if people do want the hack, I won’t object more.

**Comment by leogermond** [comment]
I do have the same issue with pip and libadalang, but as you said @pmderodat  that's coming from the fact I'm using our internal anod system to get the libadalang build, so that's obviously not a good use case for portability. Using GNATtracker's libadalang release works as intended.

**Comment by leogermond** [comment]
Sorry guys !

**Comment by setton** [comment]
> 

Honestly, even after reading the setuptools doc, I feel like it would be more convenient from me to keep the script - it's the difference between one step and zero step. 

Also since I'm working in the same environment as GNAT Studio / VS Code / Ada Language Server, I prefer to get the same python-with-libadalang with adareducer as with the other tools...

**Comment by pmderodat** [comment]
Alright, then approving

**Review by pmderodat — APPROVED** [review]

**Pull request merged**
